# Site settings
lang: en-AU
title: Steph & Matt
email: matthew.pomaroff@gmail.com
description: Stephanie Li and Matthew Pomaroff's WEdding
baseurl: ""
url: "https://pomaroff.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
    style: compressed